### ISSUE TITLE
Thank you for making the project active again!

### ISSUE THREAD

**Issue by gshakir** [criticalstack/libevhtp#1]

**Comment by qianguozheng** [comment]
I think it's better to add redirect to here instead of deleting old repository.

**Comment by NathanFrench** [comment]
Once the project was transferred, @errzey just put in an empty repo with a README pointing to this. 

Is that enough? Other than that, not quite sure if I can do a 301.

Thanks!

**Comment by mephux** [comment]
Thanks for taking this project over @NathanFrench! You are a true internet hero.

**Comment by pchero** [comment]
Thank you! :)

**Comment by mannol** [comment]
Thanks mate, really appreciate it!
