### ISSUE TITLE
suggest to return error code instead of abort when malloc or calloc fail

### ISSUE THREAD

**Issue by yonghuhaige** [criticalstack/libevhtp#111]
https://github.com/criticalstack/libevhtp/blob/9d0a2f370ae52df4d44115d5e95c2b034081b110/include/internal.h#L88

The behavior should be decided by lib user

**Comment by NathanFrench** [comment]
Since these are `assert()` frontends, this is actually right. But it shouldn't be compiled with `-DNDEBUG`. I fixed this here: https://github.com/criticalstack/libevhtp/commit/07d6f5f1b6192fb883819349687263caae53ef68

Thank you for pointing this out!
