### ISSUE TITLE
Will libevhtp support websocket?

### ISSUE THREAD

**Issue by mawenbao** [criticalstack/libevhtp#116]
Hello, I found someone implemented websocket for libevhtp here: [libevhtp2/ws](https://chromium.googlesource.com/external/github.com/ellzey/libevhtp/+/libevhtp2/src/evhtp2/ws/). Will libevhtp add this feature?

**Comment by NathanFrench** [comment]
Wow, I thought I lost that code. The answer is maybe. Would websockets be a better bet over h2 in your opinion?

**Comment by mawenbao** [comment]
OK, thank you.
