### ISSUE TITLE
[New feature] satisfy the https private key decrypt requirement

### ISSUE THREAD

**Issue by helinbo2015** [criticalstack/libevhtp#16]
### 1. feature background  
As a https server, for better security consideration, user may not keep the  private key(for example: named as tls.key) in a clear text. it may use some encryption algo to encrypt the tls.key for protecting from server inbreak. 
so when before use `tls.key` to create a https connection,  user first decrypt the tls.key.  

### 2. current implementation  
now, in the `evhtp_ssl_init()`,  `cfg->privfile` is used directly. this means that user should use a unencrypted privfile. user can not use a encrypted privfile.   
```
    SSL_CTX_use_PrivateKey_file(htp->ssl_ctx,
                                cfg->privfile ? cfg->privfile : cfg->pemfile, SSL_FILETYPE_PEM);
```

### 3. solution  
i'd like add a member `callback` (for example: decrypt_privfile_cb) in the `evhtp_ssl_cfg_t` struct. if this callback is set, it will be called to decrypt the privfile and used by `SSL_CTX_use_PrivateKey()`.  

@NathanFrench  if this feature is welcome, i can make a commit.  Thanks in Advance.

**Comment by NathanFrench** [comment]
This is actually a really good idea. Take the security out of the libraries hands.

I welcome this type of ingenuity.

**Comment by helinbo2015** [comment]
@NathanFrench  Please review the commit.  any suggestions are welcome.
thank you  in advance.
BTW:  i have tested the customize_decrpyt_privfile_cb in my machine and it works ok.

**Comment by NathanFrench** [comment]
Merged, thank you very much.
