### ISSUE TITLE
evhtp_send_reply_chunk does not properly chunk

### ISSUE THREAD

**Issue by mason-hale** [criticalstack/libevhtp#19]
I initially tried to implement chunked encoding using libevent but turned to this library when that didn't work out. Unfortunately, the same issue seems to persist here. I've been trying to send large amounts of data over a single HTTP request, but the amount is too large for one evhtp_send_reply. So, I turned to chunking, which seems like it should have been the perfect solution--it ostensibly sends the content in pieces so that a single buffer won't become overfilled (which causes the crashing on my machine). And yet, it doesn't work at all.

I stepped through the code using GDB (libevhtp's own test_chunking test) and found that evhtp_send_reply_chunk merely pushes the overflowing buffer back a step. The content is progressively added to req->conn->bev->output (where req is the evhtp_request_t) with each chunk call. This buffer grows until evhtp_send_reply_chunk_end flushes its content into the network. Nothing is sent over the network until all the chunks have been loaded into this intermediary buffer, a confounding discovery that seems to eliminate all utility of this encoding method. (The bufferevent_flush call at the end of chunk seems to do nothing at all--digging down, it ultimately calls libevent's be_socket_flush function, which just returns 0 because of course.) I furthermore did a practical test in which I inserted sleep calls in between the chunk calls and, indeed, the server simply hanged until all the sleep and chunk calls had gone through. If chunking were working properly, pieces of the request should have been sent incrementally.

Am I missing something? It just doesn't seem like chunking is working at all like it's supposed to. Any help would be greatly appreciated.

**Comment by NathanFrench** [comment]
Hi,

`bufferevent_flush` does nothing at the moment.

What version of libevent and libevhtp are you using to test?

**Comment by mason-hale** [comment]
Hi Nathan,

I ended up figuring out the solution with the help of someone on the libevent git page. I was missing the event loop/event add process, which I didn't realize was necessary for chunked encoding. So my issue is no longer relevant.

**Comment by NathanFrench** [comment]
Awesome! Can you please paste what you had to do to fix this specific issue? I can annotate it.

Thanks!
