### ISSUE TITLE
Please tag a release number

### ISSUE THREAD

**Issue by rnalrd** [criticalstack/libevhtp#2]
It helps in maintaining distro packages
Thanks!

**Comment by qianguozheng** [comment]
Definitely, I could not find any release tag.

**Comment by ncopa** [comment]
Agree, i am in a release process and just discovered that libevhtp moved. No tags is a problem. Can we please have a new tag that is bigger than `1.2.11n`?

Please don't use same tag since the checksum of the tarball is changed.

Thank you for maintaining this! :heart:

**Comment by mephux** [comment]
They are back now @rnalrd @qianguozheng @ncopa
