### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by mannol** [criticalstack/libevhtp#20]
Running make install after compiling places headers in `/usr/local/evhtp/` dir (under ubuntu). Using those global headers causes compilation to fail because evhtp.h includes files assuming they are installed in `/usr/local/` dir instead.

**Comment by NathanFrench** [comment]
Wow, thanks, that's stupid. Let me fix.

**Comment by mannol** [comment]
Oh how lovely. Thank you!

**Comment by NathanFrench** [comment]
I think this is a short-term fix. What do you think?

**Comment by mannol** [comment]
It's okay as a short-term fix. It will be much better after general refactor, I'm sure.

**Comment by NathanFrench** [comment]
Yep.

**Comment by NathanFrench** [comment]
merged and closing. Thanks for pointing this out!
