### ISSUE TITLE
Using the shipped regex library brakes functionality of posix regex on glibc

### ISSUE THREAD

**Issue by mannol** [criticalstack/libevhtp#22]
I had an issue with `regexec()` always returning mismatch on any regex I tried. Removing the oniguruma's regex lib from the build solved the issue.

**Comment by NathanFrench** [comment]
Yeah, `regexec()` conflicts with POSIX regex. If I recall, if `EVHTP_DISABLE_REGEX` is OFF (enabled), and cmake can find a system version of onig `find_library(HAS_SYS_ONIG onig)`, then it will use that.

In reality, this dependency should be removed from the source tree and replaced with a in-source cmake build (add a new entry to https://github.com/NathanFrench/CMakePercolator)

**Comment by NathanFrench** [comment]
I think maybe these commits fix this:

https://github.com/criticalstack/libevhtp/commit/a59b625b8ab94e1a5aa4b06e947f87ffe3fead7a
https://github.com/criticalstack/libevhtp/commit/7b9d1a27f77734f6a6128b948a47b23fbe493fa7
