### ISSUE TITLE
SEGV on unknown address 0x0 in evhtp_get_cb()

### ISSUE THREAD

**Issue by mannol** [criticalstack/libevhtp#25]
This happens when the callbacks object is NULL. Reason is `evhtp_set_cb()` not being called beforehand.

**Comment by NathanFrench** [comment]
Details, please.

**Comment by NathanFrench** [comment]
You're going to have to work with me a little here. I can read code.

What version, how are you triggering this, code to reproduce, etc.

**Comment by mannol** [comment]
I am calling `evhtp_get_cb()` with out having set any callback beforehand.You can reproduce the segv with following code:```Cevhtp_t* h = evhtp_new(base);evhtp_get_cb(h, "/path");```Version: default git branch.

**Comment by NathanFrench** [comment]
Err. OK.

**Comment by NathanFrench** [comment]
Obviously, things don't work if you don't initialize. But I put in a "fix" for you.

**Comment by mannol** [comment]
Well, this GitHub app is useless... Thanks, it's nice to have things not crash if you read from initialized context.
