### ISSUE TITLE
Use SSL_CTX_use_certificate_chain_file instead of SSL_CTX_use_certificate_file in evhtp_ssl_init

### ISSUE THREAD

**Issue by mannol** [criticalstack/libevhtp#26]
Currently, libevhtp is using `SSL_CTX_use_certificate_file` to load a certificate file. That function lacks the ability to load the pinned certificate chain (if any) which has a consequence of connecting clients **not trusting** the received certificate. By using `SSL_CTX_use_certificate_chain_file` we give the libssl the ability to read and send the entire certificate chain (if any), which clients can check against.

**Comment by NathanFrench** [comment]
Awesome; thank you very much!
