### ISSUE TITLE
All pointers should be used before the judge if( ptr == NULL), otherwise it will cause a crash.

### ISSUE THREAD

**Issue by eerstar** [criticalstack/libevhtp#27]
htpparse_error
htparser_get_error(htparser * p) {
    return p->error;
}

I have encountered this problem many times in this project,Not just this one.

**Comment by NathanFrench** [comment]
haha I can't believe I just did a pull request of the wrong code.

**Comment by Turtleberry** [comment]
Nathan, that... was epic. LOL!

**Comment by Turtleberry** [comment]
I'm going to be pushing up something more relevant here tonight, specifically I'm starting (and plausibly finishing)... hopefully, an abstracted logger with an interleaved ring buffer for performance and minimal locking...

**Comment by NathanFrench** [comment]
Nice! I've been thinking about doing one of those for a while! 

Ages ago, we wrote something to do this on another project: 
https://github.com/mandiant/RProxy/blob/feature/ratelimiting/src/logger.c 

The idea was to use {xxx} for specific parts of the request. The container that had multiple types of inputs/outputs (even Apple's stupid ASL):

https://github.com/mandiant/RProxy/blob/feature/ratelimiting/src/lzlog.c

Both of these are pretty terrible (I mean, if()s instead switches??), but it's a start.

**Comment by NathanFrench** [comment]
Now back to the task at hand. As I was going through things, there are mixed (builtin so -NDEBUG does not remove it) assertions and normal checks.

I'm a fan of "fail close", but I don't know. I overlooked them since there was a lot of things I would have to figure out to free again. Which is why I wrote this header-only transparent reference counter:

```C
#pragma once

#include <pthread.h>

static void (* REF_free)(void *) = free;
static void * (* REF_realloc)(void *, size_t) = realloc;
static void * (* REF_malloc)(size_t) = malloc;

struct refcount_ {
    pthread_mutex_t mux;
    unsigned int    count;
    char            data[];
};

#define ref_upcast(DAT) \
    (struct refcount_ *)((char *)(DAT - offsetof(struct refcount_, data)))

#define ref_barrier(CODE)           \
    pthread_mutex_lock(&refc->mux); \
    CODE                            \
    pthread_mutex_unlock(&refc->mux)


static inline void
ref_init_functions(void *(*mallocf)(size_t),
                   void * (*callocf)(size_t, size_t),
                   void *(*reallocf)(void *, size_t),
                   void (* freef)(void *))
{
    REF_malloc  = mallocf;
    REF_realloc = reallocf;
    REF_free    = freef;
}

static unsigned int
ref_inc(void * buf)
{
    struct refcount_ * refc = ref_upcast(buf);
    unsigned int       refs;

    ref_barrier({ refs = ++refc->count; });

    return refs;
}

static unsigned int
ref_dec(void * buf)
{
    struct refcount_ * refc = ref_upcast(buf);
    unsigned int       refs;

    ref_barrier({ refc->count -= 1; refs = refc->count; });

    return refs;
}

static inline void *
ref_malloc(size_t size)
{
    struct refcount_  * refc;
    pthread_mutexattr_t attr;

    refc        = REF_malloc(sizeof(*refc) + size);
    refc->count = 1;

    pthread_mutexattr_init(&attr);
    pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
    pthread_mutex_init(&refc->mux, &attr);

    return refc->data;
}

static void
ref_free(void * buf)
{
    struct refcount_ * refc = ref_upcast(buf);

    ref_barrier({
        if (--refc->count == 0)
        {
            pthread_mutex_unlock(&refc->mux);
            return REF_free(refc);
        }
    });
}
```

If we use that, it will be easy to know when to free and not by checking the refcount.
