### ISSUE TITLE
pause / resume logic needs a makeover

### ISSUE THREAD

**Issue by wolfchimneyrock** [criticalstack/libevhtp#3]
There was this exchange in the issues of elizy's repo that I would always keep going back to, and which never formally made it into the documentation, perhaps it is worth adding to the documentation, now that those old issues are now gone?

>> I have a question : why need pause and resume pairs.

> This is actually a good question.
> 
> Pause and resume will essentially stop and start attempting to read from the client socket. But also has some extra logic around it. Since the parser is a state machine, you can get functions executed as data is passed to it. But what if you wanted to temporarily stop that input processing? Well you have to save the state on the current input, then turn off the reading.
> 
> You can do all the normal things you can do while the request is paused, add output data, headers, etc. But it isn't until you use the resume function will these actions actually happen on the socket. When resume is called, it does an event_active(), which in turn goes back to the original reader function.
> 
> For example, with my companies reverse proxy we wrote (https://github.com/mandiant/RProxy) we don't immediately send the request to a backend, they get queued up and only processed once a backend connection becomes available. If it was not for the pause functionality, if a connection started posting a crap-ton of data, it would buffer and eat up all the memory.
> 
> This source comment actually does a good job of describing: https://github.com/mandiant/RProxy/blob/master/src/rproxy.c#L1020

**Comment by NathanFrench** [comment]
Yes, without looking, pause and resume is wonky. @errzey  had a hack solution using event_active and a deferred type mechanism with a special flag.

This is OK, but I think there are edge cases where that would fail. Libevent 2.1 introduced a function that acts much like event_active, but specifically for bufferevents and does not need a signal.

I think the first step I will be taking to fix this is to implement some reference counting. I know that's been thrown around more than once; it's time to do it.

**Comment by NathanFrench** [comment]
One thing to note, without setting libevent to use deferred callbacks, each consecutive read or write is done immediately. This, of course, can cause problems when traversing backwards in the processing state.

We can think of it in this manner:

```
state1 -> write();
state2 -> read();
state3 -> error, free();
state4 -> write(); // now invalid
```

While deferred orders properly and returns back to the loop before each execution.

```
state1 -> add to defer list WRITE
state2 -> add to defer list READ
state3 -> add to defer list ERROR // short circuit here, never calling state4
```

**Comment by NathanFrench** [comment]
Merging this into https://github.com/criticalstack/libevhtp/issues/11
