### ISSUE TITLE
Segfault in test_basic when compiled w/o SSL

### ISSUE THREAD

**Issue by vvromanov** [criticalstack/libevhtp#30]
Build with SSL disabled
Execute test_basic - segfault.
With enables santizer next report generated 

 ASAN:DEADLYSIGNAL
==14636==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x7ff95654f191 bp 0x7ffcb1ccc600 sp 0x7ffcb1ccc5e0 T0)
    #0 0x7ff95654f190 in evconnlistener_free (/lib64/libevent-2.0.so.5+0x1d190)
    #1 0x4125a6 in evhtp_unbind_socket /home/vromanov/work/libevhtp/evhtp.c:3631
    #2 0x404854 in main /home/vromanov/work/libevhtp/examples/test_basic.c:53
    #3 0x7ff955967b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)
    #4 0x404568  (/home/vromanov/work/libevhtp/cmake-build-debug/examples/test_basic+0x404568)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib64/libevent-2.0.so.5+0x1d190) in evconnlistener_free
==14636==ABORTING

master branch, Centos 7.3

**Comment by NathanFrench** [comment]
Oddly enough, this is a dup of https://github.com/criticalstack/libevhtp/issues/34 which I just pushed a fix for. That seemed to fix this issue.
