### ISSUE TITLE
Don't use ${CMAKE_SOURCE_DIR} in CMakeLists.txt

### ISSUE THREAD

**Issue by vvromanov** [criticalstack/libevhtp#31]
# Details
When libevhtp included in another project using add_subdirectory(libevhtp),  CMAKE_SOURCE_DIR points to source directory of main project, not to source directory of libevhtp. To fix this problem replace with CMAKE_SOURCE_DIR with CMAKE_CURRENT_SOURCE_DIR
# Steps or code to reproduce the problem.
# Version
master and last tag

**Comment by NathanFrench** [comment]
Thank you - will have it fixed tonight!

**Comment by NathanFrench** [comment]
Fixed, thank you!
