### ISSUE TITLE
Segfault when second instance of test_basic started 

### ISSUE THREAD

**Issue by vvromanov** [criticalstack/libevhtp#32]
# Details
Compile and start test_basic, start second instance of test_basic. Second instance will be ended with segfault in evhtp_unbind_socket. htp->server==NULL
# Version
master

**Comment by NathanFrench** [comment]
DOH! I will hot-patch tonight! Thank you.

**Comment by NathanFrench** [comment]
Fixed, thank you very much. Until the next release, I suggest any code that uses this until the next release manually check the arguments before passing. It's just a wrapper around `evconnlistener_free`
