### ISSUE TITLE
evhtp_hook_on_request_fini called twice

### ISSUE THREAD

**Issue by vvromanov** [criticalstack/libevhtp#34]
# Details
evhtp_hook_on_request_fini called twice on second and next requests. This
# Steps or code to reproduce the problem.
add printf("fini\n"); to test_fini function in test.c file. Compile. Run.
make first request to localhost/bar using Chrome. One line with fini will be printed. Make another request. Two lines with "fini" will be printed.
I do some investigation and found that this issue possibly related to keepalive.  Looks like evhtp closes connection after receiving request and browser send request again. 
# Version
master, Centos 7.3

**Comment by NathanFrench** [comment]
Fixed, and a hot-patch release was made in the releases section.

![](https://i.pinimg.com/736x/75/27/10/75271005109e29e2c1c2f5a38679f536--funny-wrestling-wrestling-quotes.jpg)
