### ISSUE TITLE
bufferevent_socket_connect returns unzero, and the program exit.

### ISSUE THREAD

**Issue by helinbo2015** [criticalstack/libevhtp#36]
# Details
1. For unknown reason, `bufferevent_socket_connect()` calling in the `evhtp_connection_ssl_new()@evhtp.c` returns a unzero value, so `evhtp_assert(rc == 0)` failed.  
2. in the `evhtp_assert()`, `abort()` func is called, so the program is exit.

# My understanding of libevhtp:
libevhtp is common http(1.1) adaptor for the programs which use it. and for some unknown reason, the program exit from libevhtp is not gracefullly.  

# workaround of program abort
- libevhtp only output the error info, don't exit.   
- and returns the error to the caller.   

```
evhtp_connection_ssl_new() {
    ...
    rc = bufferevent_socket_connect(conn->bev,
                                    (struct sockaddr *)&sin, sizeof(sin));

   // the following code is workaround
   if(rc !=0 ) {
          // log error info
          // free conn
          // set conn to NULL
   }
    return conn;
}
```

# Version
the newest libevhtp

@NathanFrench  
how about the above case, any suggestions is welcome,  thank you in advance.

**Comment by NathanFrench** [comment]
> how about the above case, any suggestions is welcome, thank you in advance.

Looks good, thank you! I will be looking into this.

**Comment by NathanFrench** [comment]
Fixed, and a hot-patch release was made in the releases section.

![](https://i.pinimg.com/736x/75/27/10/75271005109e29e2c1c2f5a38679f536--funny-wrestling-wrestling-quotes.jpg)

**Comment by NathanFrench** [comment]
Can you print me the actual return value you are getting just to satisfy my own curiosity?

**Comment by helinbo2015** [comment]
@NathanFrench 
until  now, `bufferevent_socket_connect() returns unzero` issue  happened only one time.  so i  didn't get the concrete return value.  and sorry for unenough info.

**Comment by NathanFrench** [comment]
I checked out libevent source. And the only return value I saw was either 0 or -1. So I was a bit confused.

Adding some error checking is easy enough - don't need to debate that.

Thanks again!

**Comment by helinbo2015** [comment]
@NathanFrench  
Thank you for your reply.
my original idea is not to analyze the reason of  `bufferevent_socket_connect()`  calling error.  i  want to discuss  is that program is `abort` from libevhtp is not graceful,  libevhtp should not terminate the program that uses libevhtp and returns `NULL`  value only.

**Comment by NathanFrench** [comment]
Yup I discussed this a bit here: https://github.com/criticalstack/libevhtp/issues/27 (last comment).

The assertions are stupid; I have no idea what he was thinking - but there is a lot of wtf here. Trust me, I'm working on that :)

**Comment by NathanFrench** [comment]
OK, should be fixed in https://github.com/criticalstack/libevhtp/pull/53
