### ISSUE TITLE
why the example(test_basic,test) crash?

### ISSUE THREAD

**Issue by lihp1603** [criticalstack/libevhtp#37]
# Details
    Starting program: /work/github/libevhtp-1.2.12/build/examples/test 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
*** Error in `/work/github/libevhtp-1.2.12/build/examples/test': double free or corruption (out): 0x00007fffffffd6a0 ***

Program received signal SIGABRT, Aborted.
0x00007ffff6da4cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: 没有那个文件或目录.
(gdb) bt
#0  0x00007ffff6da4cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6da80d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6de1394 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff6eefb28 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff6ded66e in malloc_printerr (ptr=<optimized out>, str=0x7ffff6eefc58 "double free or corruption (out)", action=1) at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x0000000000406ce4 in htp__free_ (ptr=0x7fffffffd6a0) at /work/github/libevhtp-1.2.12/evhtp.c:173
#6  0x000000000040c1e3 in evhtp_kv_free (kv=0x6847b0) at /work/github/libevhtp-1.2.12/evhtp.c:2968
#7  0x000000000040c327 in evhtp_kvs_free (kvs=0x6835a0) at /work/github/libevhtp-1.2.12/evhtp.c:3007
#8  0x0000000000408611 in htp__request_free_ (request=0x6833c0) at /work/github/libevhtp-1.2.12/evhtp.c:1091
#9  0x000000000040aae6 in htp__connection_writecb_ (bev=0x682a90, arg=0x680890) at /work/github/libevhtp-1.2.12/evhtp.c:2201
#10 0x00007ffff7bad0df in bufferevent_writecb (fd=<optimized out>, event=<optimized out>, arg=0x682a90) at bufferevent_sock.c:297
#11 0x00007ffff7ba2a10 in event_persist_closure (ev=<optimized out>, base=0x67f040) at event.c:1319
#12 event_process_active_single_queue (activeq=0x67f480, base=0x67f040) at event.c:1363
#13 event_process_active (base=<optimized out>) at event.c:1438
#14 event_base_loop (base=0x67f040, flags=0) at event.c:1639
#15 0x0000000000406c3e in main (argc=1, argv=0x7fffffffe408) at /work/github/libevhtp-1.2.12/examples/test.c:663
(gdb) 
# Steps or code to reproduce the problem.
    examples/test 
# Version 
   libevhtp-1.2.12 
   libevent-2.0.2

**Comment by NathanFrench** [comment]
Ha, yeah this was fixed right after I pushed 1.2.12.

https://github.com/criticalstack/libevhtp/releases/tag/1.2.12-1 fixes it.
