### ISSUE TITLE
Client requests cause assertion error

### ISSUE THREAD

**Issue by AnatolyPopov** [criticalstack/libevhtp#42]
# Details
When I tried to run test_client example I got following assertion error

> Assertion failed: c && c->htp && c->request && c->parser && bev (htp__connection_writecb_: libevhtp/evhtp.c:2165)

Seems the reason of this is that a client connection is every time created with evhtp_t equal to NULL, like on line 5173 in evhtp.c

```
  if (!(conn = htp__connection_new_(NULL, -1, evhtp_type_client)))
  {
      return NULL;
  }
```
And there is an assertion in evhtp.c on line 2165

`evhtp_assert(c && c->htp && c->request && c->parser && bev);`

So with client request c->htp is every time NULL and assertion fails.

# Steps or code to reproduce the problem.
Simply run test_client.c
# Version
Latest libevhtp version.

**Comment by NathanFrench** [comment]
Client support has always been lacking; I know I know. @errzey was fairly upfront about libevent having a better client API. But I think this should change :)

I am handing this off to a great engineer who will be assisting me in further development. And will have you a fix ASAP!

Thank you very much!

**Comment by sftwrngnr** [comment]
I'll get on this, and include test cases to validate the fix.
Thanks,
Dan

**Comment by AnatolyPopov** [comment]
Thanks a lot for this! I'm also able to work on a solution if you need any help.

**Comment by NathanFrench** [comment]
Thanks @sftwrngnr! Going to review the pull request tonight and have a release made.

**Comment by NathanFrench** [comment]
#46 has now turned into a refactor due to this issue :)

**Comment by NathanFrench** [comment]
OK, changes have been merged into develop. Thank you for your input!
