### ISSUE TITLE
evhtp_send_reply_chunk  evhtp_send_reply memoryleak

### ISSUE THREAD

**Issue by sunchengbi** [criticalstack/libevhtp#45]
# Details 
code as flows：
```C
  void reqHandler(evhtp_request_t *req,void *arg)
{
        evhtp_send_reply_chunk_start(req, EVHTP_RES_OK);
        struct evbuf_t * buffer = evbuffer_new();
        assert(buffer);
        char buf[4096];
        int i;
       
        for(i=0; i < 10000; i++)
        {
                evbuffer_add(buffer, buf, 4096);
                evhtp_send_reply_chunk(req, buffer);
                evbuffer_drain(buffer, -1);
        }

        evhtp_send_reply(req, EVHTP_RES_OK);

        evbuffer_free(buffer);

}

int main(int argc,char **argv)
{
        evbase_t          * evbase;
        evhtp_t           * evhtp;

        evbase            = event_base_new();
        assert(evbase);
        evhtp             = evhtp_new(evbase, NULL);
        assert(evhtp);

        evhtp_set_gencb(evhtp, reqHandler, NULL);
        int ret = evhtp_use_threads(evhtp, NULL, 4, NULL);

        ret = evhtp_bind_socket(evhtp, "0.0.0.0", 9010, 1024);

        ret = event_base_loop(evbase, 0);
}
```

# Steps or code to reproduce the problem.
     memory leak ，how to do ? who can help me,thanks

# Version
libevhtp-1.2.12-1

**Comment by NathanFrench** [comment]
`evhtp_send_reply(req. EVHTP_RES_OK);` needs to be replaced by  `evhtp_send_reply_chunk_end(req);`

**Comment by NathanFrench** [comment]
Closing since this was a simple misusage of the API.

Thank you very much for helping us out @sunchengbi!

**Comment by sunchengbi** [comment]
Thank you !
I test with your code and still have memory leaks。@NathanFrench


  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                                                                    
 2740 root      20   0 13.0g 9.1g 1552 S 254.0 59.2   3:05.04 memonry-leak.1.

**Comment by NathanFrench** [comment]
https://github.com/criticalstack/libevhtp/blob/develop/examples/example_chunked.c
