### ISSUE TITLE
evhtp_set_gencb don't work

### ISSUE THREAD

**Issue by vvromanov** [criticalstack/libevhtp#51]
# Details
# Steps or code to reproduce the problem.

evhtp_set_gencb don't work. Instead first evhtp_set_cb callback called.

* Compile code
* request http://localhost:8081/
* You will get "simple" instead of "root"
* Same result if you request http://localhost:8081/some_random_text_jfjfjfj

## Example code (if applicable)

This is modified version of test_basic.c

```C
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <errno.h>
#include <evhtp.h>

void
testcb(evhtp_request_t * req, void * a) {
    const char * str = a;

    evbuffer_add(req->buffer_out, str, strlen(str));
    evhtp_send_reply(req, EVHTP_RES_OK);
}

void
issue161cb(evhtp_request_t * req, void * a) {
    struct evbuffer * b = evbuffer_new();

    if (evhtp_request_get_proto(req) == EVHTP_PROTO_10) {
        evhtp_request_set_keepalive(req, 0);
    }

    evhtp_send_reply_start(req, EVHTP_RES_OK);

    evbuffer_add(b, "foo", 3);
    evhtp_send_reply_body(req, b);

    evbuffer_add(b, "bar\n\n", 5);
    evhtp_send_reply_body(req, b);

    evhtp_send_reply_end(req);

    evbuffer_free(b);
}

int
main(int argc, char ** argv) {
    evbase_t * evbase = event_base_new();
    evhtp_t  * htp    = evhtp_new(evbase, NULL);

    evhtp_set_cb(htp, "/simple/", testcb, "simple");
    evhtp_set_cb(htp, "/1/ping", testcb, "one");
    evhtp_set_cb(htp, "/1/ping.json", testcb, "two");
    evhtp_set_cb(htp, "/issue161", issue161cb, NULL);
// VVVVVVVVVVVVVVVVVVVVVVVVV
    evhtp_set_gencb(htp, testcb, "root");
// ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef EVHTP_DISABLE_EVTHR
    evhtp_use_threads_wexit(htp, NULL, NULL, 8, NULL);
#endif
    evhtp_bind_socket(htp, "0.0.0.0", 8081, 2048);

    event_base_loop(evbase, 0);

    evhtp_unbind_socket(htp);
    evhtp_free(htp);
    event_base_free(evbase);

    return 0;
}
```

# Version
Latest

**Comment by NathanFrench** [comment]
Neato, big fail here.

As seen in the referenced commit above, I think this is a fix.

Can you try the https://github.com/criticalstack/libevhtp/tree/issue51 branch?

**Comment by NathanFrench** [comment]
Merged into develop. Thank you very much for pointing out this incredibly silly bug. 

It reminds me of a story from the book "Deep C Secrets". I cannot quote the entire thing, but the gist was this: There was a bug in Solaris's mail command. Any user that had an "s" as the second character of their name would never receive email. Turns out there was a command line parsing bug; It was treating the first character as a `-` and looking ahead at the `s`, thinking it was `-s` (or something like this).

**Comment by vvromanov** [comment]
Fixed!

**Comment by NathanFrench** [comment]
![](https://us.v-cdn.net/5020794/uploads/editor/rp/jp39djxpcq1y.gif)
