### ISSUE TITLE
evhtp_set_regex_cb() makes crash

### ISSUE THREAD

**Issue by pchero** [criticalstack/libevhtp#66]
# Details
Hi, 

After compile libevhtp with oniguruma package in ubuntu-14.04, call evhtp_set_regex_cb() function makes crash.

# Steps or code to reproduce the problem.
- Install oniguruma package using apt-get
-- $sudo apt-get install libonig-dev
- Install libevhtp
- compile sample code

## Example code (if applicable)
```C

#include <stdio.h>
#include <stdlib.h>
#include <evhtp.h>

void testcb(evhtp_request_t *req, void *a)
{
  const char* str;
  
  printf("Fired testcb.\n");
  str = a;
  
  evbuffer_add_printf(req->buffer_out, "%s", str);
  evhtp_send_reply(req, EVHTP_RES_OK);
}

int main(int argc, char** argv)
{
  evbase_t *evbase;
  evhtp_t *htp;
  
  evbase = event_base_new();
  htp = evhtp_new(evbase, NULL);
  
#ifndef EVHTP_DISABLE_REGEX
  printf("NOT defined EVHTP_DISABLE_REGEX.\n");
  
  evhtp_set_regex_cb(htp, "/simple1/*", testcb, "/simple/");
#endif
    
  evhtp_bind_socket(htp, "0.0.0.0", 8081, 1024);
  
  event_base_loop(evbase, 0);
  
  evhtp_unbind_socket(htp);
  evhtp_free(htp);
  event_base_free(evbase);
  
  return 0;
}

...

$ ./main &
[1] 23672
$ NOT defined EVHTP_DISABLE_REGEX.

$ curl -X GET localhost:8081/simple1/test
curl: (52) Empty reply from server
[1]+  Segmentation fault      (core dumped) ./main

```

# Version
$ git branch -v
* develop d890899 added some new functions to examples/eutils

**Comment by pchero** [comment]
I've just tested with onig-6.7.0. But seems like it's the same.

**Comment by NathanFrench** [comment]
Can you try adding `-lonig` to your compile flags? Since I removed the built-in dependency, the system may be attempting to use the POSIX-regex. This will override that.

Seemed to have fixed it for me; I'll add it to the pkg-config file if it works for you too.

Thanks!

**Comment by pchero** [comment]
Perfect. :)

It's working! Thanks.

Please feel free to close the ticket. :)

**Comment by NathanFrench** [comment]
No problemo, thank you very much!
