### ISSUE TITLE
error: incomplete definition of type 'struct evhtp_callback_s'

### ISSUE THREAD

**Issue by Ultima1252** [criticalstack/libevhtp#68]
# Details
I'm trying upgrade libevhtp on FreeBSD ports, but running into compilation errors that I can't quite figure out how to fix.

Sorry, forgot to provide full error:
upload-file.c:2373:23: error: incomplete definition of type 'struct evhtp_callback_s'
    evhtp_set_hook(&cb->hooks, evhtp_hook_on_headers, upload_headers_cb, NULL);
                               ~~^
/usr/local/include/evhtp/evhtp.h:38:8: note: forward declaration of 'struct evhtp_callback_s'
struct evhtp_callback_s;
          ^
[1] Is a full log of the build if interested.

All the evhtp_set_hook function calls return this error in the below Example code link.

[1] https://poudriere.ultimasbox.com/data/111amd64-test/2018-01-02_08h54m49s/logs/errors/seafile-server-6.2.3.log
# Steps or code to reproduce the problem.
1. Install FreeBSD with the ports collection.
2. Patch libevhtp with [2].
3. cd /usr/ports/net-mgmt/seafile-server && make
4. Error mentioned x 11

[2] https://reviews.freebsd.org/D13742
## Example code (if applicable)
https://github.com/haiwen/seafile-server/blob/20da7d028e9b80704f0d89c7e06b606d03200ef1/server/upload-file.c#L2342

# Version
1.2.11 (works) --> 1.2.15 (breaks)

# Special Thanks
Thanks for taking over this library. It definitely has many areas that need improvement but is promising. Using an out dated Oniguruma was driving me absolutely crazy! Thank you so much for moving this out of the source.

**Comment by NathanFrench** [comment]
`evhtp_unset_hook` has been warning of depreciation for the last few releases. The following can be used instead:

```C
EVHTP_EXPORT int evhtp_connection_set_hook(evhtp_connection_t * c, evhtp_hook_type type, evhtp_hook cb, void * arg);
EVHTP_EXPORT int evhtp_request_set_hook(evhtp_request_t * r, evhtp_hook_type type, evhtp_hook cb, void * arg);
EVHTP_EXPORT int evhtp_callback_set_hook(evhtp_callback_t * cb, evhtp_hook_type type, evhtp_hook hookcb, void * arg);

EVHTP_EXPORT evhtp_hooks_t * evhtp_connection_get_hooks(evhtp_connection_t * c);
EVHTP_EXPORT evhtp_hooks_t * evhtp_request_get_hooks(evhtp_request_t * r);
EVHTP_EXPORT evhtp_hooks_t * evhtp_callback_get_hooks(evhtp_callback_t * cb);

EVHTP_EXPORT int evhtp_unset_all_hooks(evhtp_hooks_t ** hooks);

EVHTP_EXPORT int evhtp_request_unset_hook(evhtp_request_t * req, evhtp_hook_type type);
EVHTP_EXPORT int evhtp_connection_unset_hook(evhtp_connection_t * conn, evhtp_hook_type type);
EVHTP_EXPORT int evhtp_callback_unset_hook(evhtp_callback_t * callback, evhtp_hook_type type);
```

I've slowly been getting this code to a point where structures like this, which should not be exposed, are only accessible via getters and setters. (This makes future development easier for the API, and easier to understand as a user).

Thanks for the Thanks!

**Comment by Ultima1252** [comment]
Thanks for the direction. C isn't my sharpest tool in my shed. Does this look correct?

`cb = evhtp_set_regex_cb (htp, "^/update-blks-aj/.*", update_blks_ajax_cb, NULL);
evhtp_set_hook(&cb->hooks, evhtp_hook_on_headers, upload_headers_cb, NULL);`
to
`cb = evhtp_set_regex_cb (htp, "^/update-blks-aj/.*", update_blks_ajax_cb, NULL);
evhtp_callback_set_hook(cb, evhtp_hook_on_headers, upload_headers_cb, NULL);`

**Comment by NathanFrench** [comment]
You got it!

Have a great new year!

**Comment by Ultima1252** [comment]
Thanks have you have a wonderful new year as well!
