### ISSUE TITLE
The function `htparser_run` may have a out of bounds memory write

### ISSUE THREAD

**Issue by lixiangyun** [criticalstack/libevhtp#69]
Although there had judged upper limit
https://github.com/criticalstack/libevhtp/blob/bc52552641ef9d01713c6d8e9b41aa1c089091fe/parser.c#L728

But, if `p->buf_idx` arrival at (`PARSER_STACK_MAX-1`) value,  The following will using two characters of space, then have a out of bounds memory write.
https://github.com/criticalstack/libevhtp/blob/bc52552641ef9d01713c6d8e9b41aa1c089091fe/parser.c#L776-L777

Proposed using `if (p->buf_idx >= PARSER_STACK_MAX-1)` replace.

**Comment by NathanFrench** [comment]
Hey Nathan, it's 1997 calling!

I'll fix this up shortly. Thank you very much!

**Comment by NathanFrench** [comment]
Can you check out https://github.com/criticalstack/libevhtp/compare/issue_69 and see if this seems resolved to you?

**Comment by NathanFrench** [comment]
I ran through a bunch of tests, and this macro doesn't seem to change anything other than the 1 byte check. So I'm going to merge and close this out.

Thanks mucho!
