### ISSUE TITLE
Convert htparse to httparser (we lost the parser war)

### ISSUE THREAD

**Issue by NathanFrench** [criticalstack/libevhtp#7]
Now that the parser war is over, let's figure out the best plan of action to replace htparser with httparser.

**Comment by mannol** [comment]
Great to see this project is being maintained. What's the reason for switch to httparser? Performance, stability, etc?

**Comment by NathanFrench** [comment]
### I'd rather blame obscure code on someone else :)

Silliness aside: I've been going back and forth on this one, last I checked `htparser` is faster, but probably not as feature-rich as `http-parser`. Currently I've got bigger fish to fry in this code; doubtful this will be dev/tested anytime soon.
