### ISSUE TITLE
the function `htparser_get_strerror` may have a out-of-bounds read

### ISSUE THREAD

**Issue by lixiangyun** [criticalstack/libevhtp#72]
# Details
# Steps or code to reproduce the problem.
1. The Array of string pointers [errstr_map](https://github.com/criticalstack/libevhtp/blob/44b503c67802beeb642dcf2d52e8cb24f3dcdb8c/parser.c#L203-217) only  have  13 item

2. But. The Enum type [htpparse_error](https://github.com/criticalstack/libevhtp/blob/44b503c67802beeb642dcf2d52e8cb24f3dcdb8c/parser.h#L51-66) had defined 14 item

3. This code  `if (e > (htparse_error_generic + 1))` may cause value  `e` large than that array `errstr_map` size. 

## Example code (if applicable)
```C
const char * htparser_get_strerror(htparser * p)
{
    htpparse_error e = htparser_get_error(p);

    if (e > (htparse_error_generic + 1))
    {
        return "htparse_no_such_error";
    }

    return errstr_map[e];
}
```

# Version
latest

**Comment by NathanFrench** [comment]
I would love to know how someone could have triggered this, since that structure is never made public, thus it was never abused; but a bug is a bug, and I fixed it up here https://github.com/criticalstack/libevhtp/commit/75574bab61f5b520e971330120f3ac4760c4a2d5

Will merge in a bit.

**Comment by NathanFrench** [comment]
All good - thanks again! You're my human static analyzer!

**Comment by lixiangyun** [comment]
I am happy to contribute to this project!
