### ISSUE TITLE
Access http return code

### ISSUE THREAD

**Issue by alpha0010** [criticalstack/libevhtp#75]
Is it possible to get the http return code from an `evhtp_hook_request_fini_cb`?  E.g., the second parameter I supply to `evhtp_send_reply()`.

**Comment by NathanFrench** [comment]
You sure can, it should be stored in `(evhtp_request_t *)req->status`. 

To make this less obtuse, I just pushed some additions to the develop branch along with examples. 

Here is an example of a `evhtp_hook_on_request_fini` function using the new code:

```C
static evhtp_res
request__callback_fini_(evhtp_request_t * req, void * arg) {
    printf("statusCode=%d statusCodeString=%s for path=%s\n",
             evhtp_request_get_status_code(req),
             evhtp_request_get_status_code_str(req),
             req->uri->path->full);
 
    return EVHTP_RES_OK;
}
```

**Comment by alpha0010** [comment]
Thanks for your prompt reply.  Unfortunately, this does not seem to be working for me.  I can put different response codes when sending a reply (for example, `evhtp_send_reply(req, 404)`), and they show up as the correctly specified response code when I access the routes from my browser.  However, regardless of response code there, within my `evhtp_hook_request_fini_cb`, `req->status` is always `200`.

**Comment by NathanFrench** [comment]
Color me red; apparently, it never stored the result upon response. Just pushed up a tiny change, should work now.

**Comment by NathanFrench** [comment]
Thanks again; Feel free to open this ticket back up if you have any more issues.
