### ISSUE TITLE
Incorrect member type of struct evthr?

### ISSUE THREAD

**Issue by hhb1029** [criticalstack/libevhtp#76]
When I see the number exit_cb, I'm confused. Because the function type named evthr_init_cb
https://github.com/criticalstack/libevhtp/blob/77f20e606e01666a8b121c2ef4c09022456cdf50/thread.c#L48

And I find the type define of callback function.
https://github.com/criticalstack/libevhtp/blob/0da6bc9d3124e225d67f5d678f1a2961987757c1/include/evhtp/thread.h#L36

**Comment by NathanFrench** [comment]
Thanks, and resolved.

Note that this was not a bug, did not affect anything, both `init_cb` and `exit_cb` were of the same type, so the alias matched the alias. Otherwise, your compiler would have either pooped out or given you a warning.

This is 100% just a readability thing.
