### ISSUE TITLE
Where is API documentation?

### ISSUE THREAD

**Issue by mlkt** [criticalstack/libevhtp#78]
I'm sorry I can't find it.

**Comment by NathanFrench** [comment]
Currently it's doxygen only; `mkdir -p html/docs && doxygen`. But this is the raw API usage; not much in the way of exact usage (and I haven't uploaded the generated output anywhere).

There are lot's of references in the [examples directory](https://github.com/criticalstack/libevhtp/tree/develop/examples). I've been slowly adding more and more examples prefixed with the word `examples_`, whereas other "examples" can be found prefixed with `test_`.

On that note, I am going to be spending the next few days doing some huge forklifts of the documentation.

**Comment by mlkt** [comment]
OK, Thank you!

**Comment by illukin** [comment]
Still no changes?
