### ISSUE TITLE
Mutex leak

### ISSUE THREAD

**Issue by isaachier** [criticalstack/libevhtp#81]
Sorry if this has already been addressed. I noticed https://github.com/criticalstack/libevhtp/blob/70849e7a310718cdc2ece4793673435179d9d452/refcount.h#L81 unlocks the mutex and frees the data, but I do not see `pthread_mutex_destroy` anywhere. Is the mutex leaked?

**Comment by NathanFrench** [comment]
Thanks, pushed changes. May need to check for `EBUSY`, but that comes later.

**Comment by isaachier** [comment]
Sounds good thanks.
