### ISSUE TITLE
Return value is ignored when 'htparser_run' in case s_body_read ?

### ISSUE THREAD

**Issue by hhb1029** [criticalstack/libevhtp#95]
https://github.com/criticalstack/libevhtp/blob/fddb411cbe7d3b873b15801501a85655f75ad597/parser.c#L2191-L2210

It seems that the res value of function 'hook_body_run'  may overwrite by the res value of function ‘hook_on_msg_complete_run’ if p->content_len == 0. I'm not sure if this is reasonable.

**Comment by NathanFrench** [comment]
You know; this showed up in a scan-build, and for whatever reason, I forgot to fix it. Thanks for bringing this up again - will have a fix later this weekend!

**Comment by NathanFrench** [comment]
Fixed https://github.com/NathanFrench/libevhtp/commit/3fa62bf5ec58cf4fc461ac5558b8464b374bca67
